trigger:
- master

parameters:
- name: 
  displayName: Environment
  type: string
  default: stage
  values:
  - stage
  - prod
pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'mohamed3laa/django'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)-${{ parameters.Environment }}'
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'k8s'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'helm/'
    overrideValues: 'image.tag=$(Build.BuildId)-${{ parameters.Environment }}'
    valueFile: 'helm/values.yaml'